config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "movies#index"
  resources :movies
  resources :casts
  resources :movies_with_casts
  resources :production_companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cast.rb
class Cast < ApplicationRecord
	include ActiveStorage::Blob::Analyzable
	validates :name, :experience, :number_of_movies, presence: true
	validates :mobile_number, :length => {:is => 10}, numericality: {only_integer: true},presence: true
	has_one_attached :profile_image

	has_many :movies_with_casts ,dependent: :destroy
	has_many :movies, :through => :movies_with_casts

	accepts_nested_attributes_for :movies_with_casts ,allow_destroy: true
end

app/models/movie.rb
class Movie < ApplicationRecord
	validates :name, :duration, presence: true
	validates :budget, numericality: {only_integer: true}, presence: true
	has_one_attached :poster
	belongs_to :production_company

	has_many :movies_with_casts ,dependent: :destroy
	has_many :casts, :through => :movies_with_casts

	accepts_nested_attributes_for :movies_with_casts ,allow_destroy: true
	accepts_nested_attributes_for :casts, allow_destroy: true
end

app/models/movies_with_cast.rb
class MoviesWithCast < ApplicationRecord
	belongs_to :movie
	belongs_to :cast
	validates :movie_id, uniqueness: { scope: :cast_id}
end

app/models/production_company.rb
class ProductionCompany < ApplicationRecord
	validates :name, :turnover, presence: true
	has_one_attached :profile_image
	has_many :movies

	accepts_nested_attributes_for :movies,allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 skip_before_action :verify_authenticity_token  
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
	include ActiveStorage::Blob::Analyzable
	def index
    @casts = Cast.all
  end

	def show
		@cast = Cast.find_by(id: params[:id])
	end

	def new
		@cast = Cast.new
	end 

	def create
		@cast = Cast.new(cast_params)
		if @cast.save
			 # @c = MoviesWithCast.create(movie_id: , cast_id: Cast.last.id)
			redirect_to movies_path
		else
			flash[:danger] = 'Something went wrong.'
      render 'new'
		end
	end

	def edit
		@cast = Cast.find_by(id: params[:id])
	end

	def update
		@cast = Cast.find_by(id: params[:id])
		@cast.update(cast_params)
		if @cast.save
			redirect_to casts_path
		end
	end

	private
	def cast_params
    params.require(:cast).permit(:name, :mobile_number, :experience, :number_of_movies, :profile_image)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include ActiveStorage::Blob::Analyzable
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find_by(id: params[:id])
    @p = ProductionCompany.find_by(id: @movie[:production_company_id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    
    if @movie.save
      redirect_to movies_path
    else
      flash[:flash] = 'Something went wrong.'
      render 'new'
    end
  end

  def destroy
  	@movie = Movie.find_by(id: params[:id])
  	if @movie.destroy
      redirect_to movies_path
    else
      flash[:danger] = 'Could not be deleted'
    end
  end

  def edit
  	@movie = Movie.find_by(id: params[:id])
  end

  def update
  	@movie = Movie.find_by(id: params[:id])
  	@movie.update(movie_params)
  	if @movie.save
      redirect_to movies_path
    else
      # flash[:danger] = @movie.errors.full_messages
      flash[:danger] = 'Something went wrong.'
      render 'new'
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :duration, :budget, :production_company_id, :poster, casts_attributes:[:id, :name, :mobile_number, :experience, :number_of_movies, :profile_image, :_destroy])
  end

end

app/controllers/movies_with_casts_controller.rb
class MoviesWithCastsController < ApplicationController
  include ActiveStorage::Blob::Analyzable
	# def new
  #   @movieswithcasts = MoviesWithCast.new
  # end

  # def create
  #   @movieswithcasts = MoviesWithCast.new(movies_with_cast_params)
    
  #   if @movieswithcasts.save
  #     redirect_to movies_path
  #   else
  #     flash[:danger] = 'Something went wrong.'
  #     render 'new'
  #   end
  # end
  def create
    @movieswithcasts = MoviesWithCast.new(movies_with_cast_params)
    if @movieswithcasts.save
      render json: {result: @movieswithcasts}, status: :created
    else 
      render json: {message: "Not saved"}, status: :unprocessable_entity
    end
  end

  private

  def movies_with_cast_params
    params.require(:movies_with_cast).permit!
  end

end

app/controllers/production_companies_controller.rb
class ProductionCompaniesController < ApplicationController

  def index
    @production_companies = ProductionCompany.all
  end
	
  def create
    @production_company = ProductionCompany.new(production_company_params)
    if @production_company.save
    	# byebug
    	# @movie = Movie.where(production_company_id: @production_company.id)
      # render json: {production_company: @production_company, movies: @movie}, status: :created
    render json: @production_company, include: :movies
    else
      render json: {errors: @production_company.errors.full_messages}
    end
  end

  private 

  def production_company_params
		params.require(:production_company).permit(:name, :turnover, movies_attributes: [:name, :budget, :duration, :_destroy])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)

    # Takes an object (@person) and creates a new instance of its associated model (:addresses)
    # To better understand, run the following in your terminal:
    # rails c --sandbox
    # @person = Person.new
    # new_object = @person.send(:addresses).klass.new
    new_object = f.object.send(association).klass.new

    # Saves the unique ID of the object into a variable. 
    # This is needed to ensure the key of the associated array is unique. This is makes parsing the content in the `data-fields` attribute easier through Javascript.
    # We could use another method to achive this.
    id = new_object.object_id

    # https://api.rubyonrails.org/ fields_for(record_name, record_object = nil, fields_options = {}, &block) 
    # record_name = :addresses
    # record_object = new_object
    # fields_options = { child_index: id }
        # child_index` is used to ensure the key of the associated array is unique, and that it matched the value in the `data-id` attribute.
        # `person[addresses_attributes][child_index_value][_destroy]`
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
        
        # `association.to_s.singularize + "_fields"` ends up evaluating to `address_fields`
        # The render function will then look for `views/people/_address_fields.html.erb`
        # The render function also needs to be passed the value of 'builder', because `views/people/_address_fields.html.erb` needs this to render the form tags.
        render(association.to_s.singularize + "_fields", f: builder)
    end

    # This renders a simple link, but passes information into `data` attributes.
        # This info can be named anything we want, but in this case we chose `data-id:` and `data-fields:`.
    # The `id:` is from `new_object.object_id`.
    # The `fields:` are rendered from the `fields` blocks.
        # We use `gsub("\n", "")` to remove anywhite space from the rendered partial.
    # The `id:` value needs to match the value used in `child_index: id`.
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	    
	end
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/movies_with_casts_helper.rb
module MoviesWithCastsHelper
end

app/helpers/production_companies_helper.rb
module ProductionCompaniesHelper
end

app/views/casts/edit.html.erb
<br><br>
<h1>Cast</h1>
<%= form_with model: @cast ,method: :patch do |form| %>
	<div>
	  <%= form.label :Name%> <%= form.text_field :name%><br><br>
	  <%= form.label :mobile_number%> <%= form.text_field :mobile_number%><br><br>
	  <%= form.label :experience%> <%= form.text_field :experience%><br><br>
	  <%= form.label :number_of_movies%> <%= form.text_field :number_of_movies%><br><br>
	  <%= form.file_field :profile_image, accept: 'image/png, image/gif, image/jpeg, image/jpg'%>
    <% @cast.errors.full_messages_for(:profile_image).each do |message| %>
    <%= message %>
    <% end %><br><br>
	</div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/casts/index.html.erb
<h1>Cast</h1>
<table>
	<tr><th>S.no</th>
	<th>Name</th>
	<th>View</th>
	<th>Delete</th></tr>
	<%@casts.each do |c|%>
			<tr><td><%= c.id%></td> <td><%= c.name%></td> <td><%= link_to 'View', cast_path(c.id)%></td><td><%= link_to 'Delete' , cast_path(c.id), method: :delete %></td> </tr>
	<%end%>
</table>
<br>
<%= link_to 'Create Cast', new_cast_path%><br><br>

app/views/casts/new.html.erb
<br><br>
<h1>Cast</h1>
<%= form_with model: @cast ,method: :post do |form| %>
	<div>
	  <%= form.label :Name%> <%= form.text_field :name%><br><br>
	  <%= form.label :mobile_number%> <%= form.text_field :mobile_number%><br><br>
	  <%= form.label :experience%> <%= form.text_field :experience%><br><br>
	  <%= form.label :number_of_movies%> <%= form.text_field :number_of_movies%><br><br>
	  <%= form.file_field :profile_image, accept: 'image/png, image/gif, image/jpeg, image/jpg'%>
    <% @cast.errors.full_messages_for(:profile_image).each do |message| %>
    <%= message %>
    <% end %><br><br>
	</div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/casts/show.html.erb
<br><br>
<p><h1><%=@cast.name%></h1><%= link_to 'Edit',edit_cast_path(@cast) %></p>
<% if @cast == nil%>
	No cast found<br>
<%else%>
	<% if @cast.profile_image.present? %>
    <%= image_tag @cast.profile_image, :size => "200x200" %>
  <%end%><br><br>
	Name : <%= @cast.name%><br><br>
	Mobile : <%= @cast.mobile_number%><br><br>
	Experience: <%= @cast.experience%><br><br>
	Number of movies: <%= @cast.number_of_movies%><br><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Threatre</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_cast_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <div>
    <%= f.label :Name%> <%= f.text_field :name%><br><br>
    <%= f.label :mobile_number%> <%= f.text_field :mobile_number%><br><br>
    <%= f.label :experience%> <%= f.text_field :experience%><br><br>
    <%= f.label :number_of_movies%> <%= f.text_field :number_of_movies%><br><br>
    <%= f.file_field :profile_image, accept: 'image/png, image/gif, image/jpeg, image/jpg'%>
    <br><br>
  <div>
    <%= link_to "Remove", '#', class: "remove_fields" %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Create</h1>
<%= form_with model: @movie, method: :put do |form| %>
	<div>
	  <%= form.select :production_company_id,options_for_select(ProductionCompany.all.map{|b| [b.name, b.id]}) %><br><br>
	  <%= form.label :Name%> <%= form.text_field :name%><br><br>
	  <%= form.label :budget%> <%= form.text_field :budget%><br><br>
	  <%= form.label :duration%> <%= form.text_field :duration%><br><br>
	  <%= form.file_field :poster, accept: 'image/png, image/gif, image/jpeg, image/jpg'%>
        <% @movie.errors.full_messages_for(:poster).each do |message| %>
        <%= message %>
        <% end %><br><br>
	</div>
  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/movies/index.html.erb
<h1>Movie</h1>
<table>
	<tr><th>S.no</th>
	<th> </th>
	<th>Name</th>
	<th> </th>
	<th>View</th>
	<th> </th>
	<th>Delete</th></tr>
	<%@movies.each do |m|%>
		<tr><td><%= m.id%></td>
			<td> </td>
			<td><%= m.name%></td>
			<td> </td>
			<td><%= link_to 'View', movie_path(m.id)%></td>
			<td> </td>
			<td><%= link_to 'Delete' , movie_path(m.id), method: :delete %></td></tr>
	<%end%>
</table>
<br>
<%= link_to 'Create Movie', new_movie_path%><br><br>
<%= link_to 'View Cast Index', casts_path%><br><br>
<%= link_to 'Add Cast to Movie', new_movies_with_cast_path%><br><br>
<%= link_to 'View Production House', production_companies_path%>

app/views/movies/new.html.erb
<h1>Create Movie</h1>
    <% if @movie.errors.any? %>
      <h2>
        <%=pluralize(@movie.errors.count, "error")%> prohibited this company :
      </h2>
      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
          <li>
          <%= msg%>
          </li>
        <% end %>
    <%end%><br><br>
<%= form_with model: @movie do |f| %>
	<div>
	  <%= f.select :production_company_id,options_for_select(ProductionCompany.all.map{|b| [b.name, b.id]}) %><br><br>
	  <%= f.label :Name%> <%= f.text_field :name%><br><br>
	  <%= f.label :budget%> <%= f.text_field :budget%><br><br>
	  <%= f.label :duration%> <%= f.text_field :duration%><br><br>
	  <%= f.file_field :poster, accept: 'image/png, image/gif, image/jpeg, image/jpg'%>
    <% @movie.errors.full_messages_for(:poster).each do |message| %>
    <%= message %>
    <% end %>
	</div>
	<div>  
    <fieldset>
        <legend>Cast: </legend>
        <%= f.fields_for :casts do |cast_form| %>
            <%= render "cast_fields", f: cast_form %> 
        <% end %>
        <%= link_to_add_fields "Add casts", f, :casts %>
    </fieldset>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/show.html.erb
<p><h1><%=@movie.name%></h1><%= link_to 'Edit',edit_movie_path(@movie) %></p>
<% if @movie.poster.present? %>
    <%= image_tag @movie.poster, :size => "200x200" %>
<%end%><br><br>
Budget : <%= @movie.budget%>cr<br>
Duration : <%= @movie.duration%><br>
Production Company : <%= @p.name%><br>
<h3>Cast </h3>
<% if @movie.movies_with_casts.present?%>
  <% @movie.movies_with_casts.each do |m| %>
    Name : <%= m.cast.name%><br>
    Mobile Number : <%= m.cast.mobile_number%><br>
    Experience : <%= m.cast.experience%><br>
    Number of Movies : <%= m.cast.number_of_movies %><br><br>
  <%end%>
<%end%>

app/views/movies_with_casts/new.html.erb
<br><br>
<h1>Add Cast To Movie</h1>
<%= form_with model: @movieswithcasts, method: :post do |form| %>
	<div>
	  <%= form.select :movie_id,options_for_select(Movie.all.map{|b| [b.name, b.id]}) %><br><br>
	  <%= form.select :cast_id,options_for_select(Cast.all.map{|b| [b.name, b.id]}) %><br><br>
	</div>
	<div>
    <%= form.submit %>
  </div>
<%end%>

app/views/production_companies/index.html.erb
<% @production_companies.each do |p| %>
	name = <%=p.name%> . turnover = <%=p.turnover%><br><br>
<%end%>